# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.30-10-ge34c767
_src_path: addons-repo-template/
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 18.0
org_name: IT-Projects LLC
org_slug: it-projects-llc
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: glitchtip-alert-telegram-bot
repo_website: https://github.com/it-projects-llc/glitchtip-alert-telegram-bot
use_pyproject_toml: true
use_ruff: true

